### ISSUE TITLE
Platform checkboxes should be radio buttons instead

### ISSUE THREAD

**Issue by nt1m** [bwinton/icons#6]
I don't think it's a very useful ability to be able to download assets from multiple platforms at once.

**Comment by aminalhazwani** [comment]
@nt1m any technical drawback if we keep the checkboxes?

**Comment by nt1m** [comment]
@aminalhazwani We would need to implement Zipping multiple assets (mobile, desktop, ...) at once.

**Comment by nt1m** [comment]
If you visually want the radio buttons to look like checkboxes, that's possible too.

**Comment by aminalhazwani** [comment]
@nt1m we are going to need  anyway the zipping because when you download icons for ios or android is always going be more than one icon. What we could do is to leave the checkboxes as they are and understand if users actually download more than one platform at the time. And once we have some data we can adapt the UI accordingly. Sounds like a plan?

**Comment by nt1m** [comment]
@aminalhazwani Sounds good, but I'm still not too convinced that ability is really useful, because iOS/Android/Desktop/Web assets are used by different teams, and it's unlikely that one team/engineer will need to download multiple platforms at once.

**Comment by nt1m** [comment]
And I actually think it may be an annoyance for someone to have to uncheck "Desktop" first before checking "iOS".

**Comment by aminalhazwani** [comment]
@nt1m yeah good point, maybe there we could uncheck the default checkbox.

**Comment by nt1m** [comment]
We would basically have radio buttons in that case :)
